from enum import Enum


class PaymentStatus(str, Enum):
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELED = "CANCELED"
    PARTIAL_CANCELED = "PARTIAL_CANCELED"
    ABORTED = "ABORTED"
    EXPIRED = "EXPIRED"


class PaymentMethod(str, Enum):
    CARD = "CARD"
    VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT"
    EASY_PAY = "EASY_PAY"
    MOBILE_PHONE = "MOBILE_PHONE"
    TRANSFER = "TRANSFER"
    CULTURE_GIFT_CERTIFICATE = "CULTURE_GIFT_CERTIFICATE"
    BOOK_CULTURE_GIFT_CERTIFICATE = "BOOK_CULTURE_GIFT_CERTIFICATE"
    GAME_CULTURE_GIFT_CERTIFICATE = "GAME_CULTURE_GIFT_CERTIFICATE"
    UNKNOWN = "UNKNOWN"
